version: '3'
services:
  dot:
    build:
      context: .
      dockerfile: Dockerfile.centos
      args:
        HOME: ${HOME}
        USER_NAME: ${USER_NAME}
        GROUP_NAME: ${GROUP_NAME}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    #user: ${USER_ID}:${GROUP_ID}
    working_dir: /home/${USER_NAME}/workspace
    volumes:
      - ${HOME}/workspace:/home/${USER_NAME}/workspace
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
    command: sleep infinity
