version: '3'
services:
  dot:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
      args:
        HOME: ${HOME}
        UNAME: ${UNAME}
        GNAME: ${GNAME}
        UID: ${UID}
        GID: ${GID}
    #user: ${UID}:${GID}
    working_dir: /home/${USER}
    volumes:
      - ${HOME}:/home/${USER}
      #- /etc/group:/etc/group:ro
      #- /etc/passwd:/etc/passwd:ro
      #- /etc/shadow:/etc/shadow:ro
      #- /etc/sudoers:/etc/sudoers:ro
    command: sleep infinity
