version: '3'
services:
  dot:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    user: $UID:$GID
    working_dir: $HOME
    volumes:
      - ${HOME}:${HOME}
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
    command: sleep infinity
